server {
    listen 80;
    server_name _;

    root /var/www/html;
    index index.html;

    access_log /dev/stdout;
    error_log /dev/stderr warn;

    location ~ /\.(?!well-known) {
        return 444;
    }

    location ~* \.(env|ini|log|conf|sql|bak|old|swp|dist)$ {
        return 444;
    }

    location ^~ /backend/static/ {
        alias /app/staticfiles/;
    }

    location ^~ /backend/docs/ {
        alias /app/site/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
